[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors * 'self' https://*.framer.app https://*.framer.website https://*.framercanvas.com"
    Access-Control-Allow-Origin = "*"
